<?php
/**
 * UnderStrap ACF specific
 *
 * @package UnderStrap
 */

// Exit if accessed directly.
defined( 'ABSPATH' ) || exit;


//resources
function resource_image(){
    if(get_field('featured_image')){
        $img_data = get_field('featured_image');
        $url = $img_data['url'];
        $alt = $img_data['alt'];
        return "<img src='{$url}' alt='{$alt}' class='resource_image'>";
    } else {
        $img_url = get_stylesheet_directory_uri() . '/imgs/green-triangles.png';
        return "<img src='{$img_url}' alt='Random image meant to convey the idea of data.' class='resource-image'>";
    }
}

function econ_details($field){
    if(get_field($field)){
        $html = '';
        $resources = get_field($field);
        //var_dump($resources);
        foreach ($resources as $key => $resource) {
            // code...
            $name = $resource->name;
            $html .= "<div class='resource-item'>{$name}</div>";
        }
        return $html;
    } else {
        return 'Not found.';
    }
}


/** add additional classes / id to the facetwp-template div generated by a facetwp 
 ** layout template
 **/
add_filter( 'facetwp_shortcode_html', function( $output, $atts) {
    if ( $atts['template'] = 'example' ) { // replace 'example' with name of your template
    /** modify replacement as needed, make sure you keep the facetwp-template class **/
        $output = str_replace( 'class="facetwp-template"', 'class="facetwp-template row"', $output );
    }
    return $output; 
}, 10, 2 );


    //save acf json
        add_filter('acf/settings/save_json', 'econ_portal_json_save_point');
         
        function econ_portal_json_save_point( $path ) {
            
            // update path
            $path = get_stylesheet_directory() . '/acf-json'; //replace w get_stylesheet_directory() for theme
            
            
            // return
            return $path;
            
        }


        // load acf json
        add_filter('acf/settings/load_json', 'econ_portal_json_load_point');

        function econ_portal_json_load_point( $paths ) {
            
            // remove original path (optional)
            unset($paths[0]);
            
            
            // append path
            $paths[] = get_stylesheet_directory()  . '/acf-json';//replace w get_stylesheet_directory() for theme
            
            
            // return
            return $paths;
            
        }